# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  quality_checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx
        pipx install uv
        # install dependencies with uv to system (don't need venv in ephemeral job)
        uv pip install --system mypy ruff pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint
      run: |
        # Lint with ruff
        ruff check --verbose --statistics --output-format github --target-version py312
    - name: Type Check with mypy
      run: |
        mypy --verbose --python-version 3.12 --strict --pretty src
    - name: Test with pytest
      run: |
        pytest --cov=src/ipados_batteryhealth --cov-fail-under=50
